name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:3.6
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: npm ci

      - run: npx mocha tests/*.js
        env:
          MONGODB_URL: mongodb://localhost:27017
